In [108]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [4]:
a[2]

12

In [16]:
len(a)

12

In [32]:
#1. How many negative numbers are there?
(a<0).sum() #I do not understand how sum() works here. Looks like it acts as a count.
#Why does it need to be in ()?

4

In [45]:
#2. How many positive numbers are there?
(a>0).sum()

5

In [54]:
#3. How many even positive numbers are there?
for number in a:
    if number % 2 == 0 and number >0:
        print(number.sum())

4
10
12


In [ ]:
#4. If you were to add 3 to each data point, how many positive numbers would there be?

In [59]:
add_three = a + 3
add_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [60]:
add_three > 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False])

In [65]:
(add_three > 0).sum()

10

In [74]:
#5. If you squared each number, what would the new mean and standard deviation be?
square_of_numbers = np.square(a)
square_of_numbers

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [80]:
#mean
square_of_numbers.mean()


74.0

In [82]:
#standard deviation
np.std(square_of_numbers)


144.0243035046516

In [84]:
#6. Center the data set.
#first - find the mean of the array

#mean of the array
mean_of_array = a.mean()
mean_of_array

3.0

In [88]:
np.mean(a, axis=0)

3.0

In [109]:
print(a)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


In [110]:
#second - subtract the data point
remove_mean = np.delete(a, [-2,1])
remove_mean

array([ 4, 12, 23, -2, -1,  0,  0,  0, -6, -7])

In [112]:
np.mean(remove_mean, axis=0)#Not it....mean needs to be "0".

2.3

In [117]:
#7. Calculate the z-score for each data point.
value=np.sum(a)#find the value
value

36

In [118]:
mean=np.mean(a)#find the mean
mean

3.0

In [120]:
deviation=np.std(a)#find the deviation
deviation

8.06225774829855

In [121]:
z_score = (value - mean)/deviation#equation to solve for "z_score"
z_score

4.093146241443879